version: '3'

volumes:
  static:
  database:

services:
  HelloDjango:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: HelloDjango
    container_name: HelloDjango
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: hellodjango_nginx
    container_name: hellodjango_nginx
    volumes:
      - static:/apps/HelloDjango/static
    ports:
      - "80:80"
      - "443:443"